routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Authorization, Content-Type');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Dingo\Api\Routing\Helpers;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/_token', function () {
    return csrf_token();
});

Route::group(['prefix' => 'admin'], function () {

    Route::group(['prefix' => 'account'], function () {
        Route::post('auth', 'Admin\AccountController@auth');
    });

    Route::group(['middleware' => 'checkAdmin'], function () {
        Route::group(['prefix' => 'index'], function () {
            Route::get('digest', 'Admin\AccountController@digest')->name('adminIndex');
        });

        Route::resource('types', 'Admin\TypesController');

        Route::model('terms', App\Models\Reference::class);
        Route::resource('terms', 'Admin\TermsController',  [
            'as' => 'admin'
        ]);

        Route::resource('pages', 'Admin\PagesController',  [
            'as' => 'admin'
        ]);

        Route::resource('news', 'Admin\NewsController',  [
            'as' => 'admin'
        ]);

        Route::resource('ads', 'Admin\AdsController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'tariiff'], function () {
            Route::get('add', 'Admin\TariffController@add')->name('admin.tariff.add');
            Route::get('index', 'Admin\TariffController@index')->name('admin.tariff.index');
            Route::post('store', 'Admin\TariffController@store')->name('admin.tariff.store');
            Route::get('edit/{id}', 'Admin\TariffController@edit')->name('admin.tariff.edit');
            Route::put('update/{id}', 'Admin\TariffController@update')->name('admin.tariff.update');
            Route::get('show/{id}', 'Admin\TariffController@show')->name('admin.tariff.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroy')->name('admin.tariff.destroy');
        });

        Route::group(['prefix' => 'currency'], function () {
            Route::get('add', 'Admin\TariffController@addMoney')->name('admin.currency.add');
            Route::post('store', 'Admin\TariffController@storeMoney')->name('admin.currency.store');
            Route::get('edit/{id}', 'Admin\TariffController@editMoney')->name('admin.currency.edit');
            Route::put('update/{id}', 'Admin\TariffController@updateMoney')->name('admin.currency.update');
            Route::get('show/{id}', 'Admin\TariffController@showMoney')->name('admin.currency.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroyMoney')->name('admin.currency.destroy');
        });

        Route::model('customer','App\Models\Customer');
        Route::resource('customer', 'Admin\CustomerController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'transporter'], function () {
            Route::get('addBalance', 'Admin\TransporterController@formBalance')->name('admin.transporter.formBalance');
            Route::post('addBalance', 'Admin\TransporterController@updateBalance')->name('admin.transporter.updateBalance');

            Route::get('findLocation', 'Admin\TransporterController@findLocation')->name('admin.transporter.findLocation');
            Route::get('approveLocation/{order}', 'Admin\TransporterController@approveLocation')->name('admin.transporter.approveLocation');
            Route::get('deleteLocation/{order}', 'Admin\TransporterController@deleteLocation')->name('admin.transporter.deleteLocation');

            Route::get('deviceChange', 'Admin\TransporterController@deviceChange')->name('admin.transporter.deviceChange');
            Route::get('approveDevice/{token}', 'Admin\TransporterController@approveDevice')->name('admin.transporter.approveDevice');
            Route::get('deleteDevice/{token}', 'Admin\TransporterController@deleteDevice')->name('admin.transporter.deleteDevice');


            Route::get('block/{user}', 'Admin\TransporterController@block')->name('admin.transporter.block');
            Route::post('blockInit/{user}', 'Admin\TransporterController@blockInit')->name('admin.transporter.blockInit');
        });

        Route::model('transporter','App\Models\Transporter');
        Route::resource('transporter', 'Admin\TransporterController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'orders'], function () {
            Route::post('punishing/{id}', 'Admin\OrderController@punishing')->name('admin.orders.punishing');
            Route::get('punish/{id}', 'Admin\OrderController@punish')->name('admin.orders.punish');
            Route::get('moderate/{id}', 'Admin\OrderController@moderate')->name('admin.orders.moderate');
            Route::get('status/{id}', 'Admin\OrderController@byStatus')->name('admin.orders.byStatus');
            Route::get('customer/{id}', 'Admin\OrderController@byCustomer')->name('admin.orders.byCustomer');
            Route::get('transporter/{id}', 'Admin\OrderController@byTransporter')->name('admin.orders.byTransporter');
        });


        Route::resource('order', 'Admin\OrderController',  [
            'as' => 'admin'
        ]);

        Route::resource('location', 'Admin\LocationsController',  [
            'as' => 'admin'
        ]);
    });
});



$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['prefix' => 'v1'], function ($api) {

        $api->group(['prefix' => 'news'], function ($api) {
            $api->get('all', 'App\Http\Controllers\NewsController@all');
            $api->get('fetch/{news}', 'App\Http\Controllers\NewsController@fetch');
        });

        $api->group(['prefix' => 'pages'], function ($api) {
            $api->get('about', 'App\Http\Controllers\PagesController@about');
            $api->get('help', 'App\Http\Controllers\PagesController@help');
            $api->get('map', 'App\Http\Controllers\PagesController@map');
        });


        $api->group(['prefix' => 'customer'], function ($api) {
            $api->group(['prefix' => 'ads'], function ($api) {
                $api->post('list', 'App\Http\Controllers\Customer\AdsController@listing');
            });

            $api->group(['prefix' => 'account'], function ($api) {

                $api->post('signUp', 'App\Http\Controllers\Customer\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Customer\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Customer\AccountController@resetPassword');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('fetch', 'App\Http\Controllers\Customer\AccountController@fetch');
                    $api->post('update', 'App\Http\Controllers\Customer\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Customer\AccountController@setPassword');
                });
            });

            $api->group(['prefix' => 'orders'], function ($api) {
                $api->get('references', 'App\Http\Controllers\Customer\OrdersController@references');
                $api->get('tariff', 'App\Http\Controllers\Customer\OrdersController@tariff');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('add', 'App\Http\Controllers\Customer\OrdersController@addOrder');
                    $api->post('my', 'App\Http\Controllers\Customer\OrdersController@myOrders');
                    $api->post('fetch/{id}', 'App\Http\Controllers\Customer\OrdersController@fetch');
                    $api->post('complete', 'App\Http\Controllers\Customer\OrdersController@complete');
                    $api->post('findLocation/{id}', 'App\Http\Controllers\Customer\OrdersController@findLocation');
                });
            });
        });


        $api->group(['prefix' => 'transporter'], function ($api) {
            $api->group(['prefix' => 'account'], function ($api) {
                $api->post('signUp', 'App\Http\Controllers\Transporter\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Transporter\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Transporter\AccountController@resetPassword');

                $api->group(['middleware' => 'checkDevice'], function ($api) {
                    $api->any('fetch', 'App\Http\Controllers\Transporter\AccountController@fetch');
                    $api->any('update', 'App\Http\Controllers\Transporter\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Transporter\AccountController@setPassword');
                    $api->post('notifications', 'App\Http\Controllers\Transporter\AccountController@notifications');
                });
            });

            $api->group(['prefix' => 'cars', 'middleware' => 'checkDevice'], function ($api) {
                $api->post('myCars', 'App\Http\Controllers\Transporter\CarsController@myCars');
                $api->post('fetchCar', 'App\Http\Controllers\Transporter\CarsController@fetchCar');
                $api->post('addCar', 'App\Http\Controllers\Transporter\CarsController@addCar');
                $api->post('addImage', 'App\Http\Controllers\Transporter\CarsController@addImage');
                $api->any('listOptions', 'App\Http\Controllers\Transporter\CarsController@listOptions');
            });

            $api->group(['prefix' => 'filter', 'middleware' => 'checkDevice'], function ($api) {

app/Models/Ads.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Ads extends Model
{
    public $guarded = ['id'];
    public $table = 'ads';
    public $timestamps = false;
}

app/Http/Controllers/Admin/AdsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Ads;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list = Ads::all();
        return view('dashboard.ads.index', compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ads = Ads::find($id);
        $allowedMimeTypes = ['image/jpeg', 'image/gif', 'image/png'];

        if ($request->has('link')) {
            $ads->link = $request->input('link');
        }

        if ($request->hasFile('image')) {
            if (in_array($request->image->getMimeType(), $allowedMimeTypes) ) {
                $tmpName = $request->image->store($id, 'banners');
                $ads->image = 'http://'.$_SERVER['HTTP_HOST'] . '/uploads/banners/'.$tmpName;
            } else {
                dd('not an image');
            }
        }

        $ads->save();

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Customer/AdsController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Helpers\ResponseHelper;
use App\Http\Controllers\Controller;
use App\Models\Ads;
use Validator;

class AdsController extends Controller
{
    public function listing() {
        return ResponseHelper::showResponse(Ads::all());
    }
}

resources/views/dashboard/ads/create.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Новости</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{ route('admin.news.store') }}" class="card">
                            {{ csrf_field() }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Добавить новость
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_ru">Russian</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_en" class="form-control" name="title_ru" value="" placeholder="Название новости на русском" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_kk">Kazakh</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_kk" class="form-control" name="title_kk" value="" placeholder="Название новости на казахском" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_en">English</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_en" class="form-control" name="title_en" value="" placeholder="Название новости на английском" required>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="content_ru">Содержание на русском</label>
                                    <div class="col-md-9">
                                        <textarea id="content_ru" name="content_ru" rows="9" class="form-control trumbowyg" placeholder=""></textarea>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="content_kk">Содержание на казахском</label>
                                    <div class="col-md-9">
                                        <textarea id="content_kk" name="content_kk" rows="9" class="form-control trumbowyg" placeholder=""></textarea>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="content_en">Содержание на английском</label>
                                    <div class="col-md-9">
                                        <textarea id="content_en" name="content_en" rows="9" class="form-control trumbowyg" placeholder=""></textarea>
                                    </div>
                                </div>


                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Добавить</button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/ads/edit.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Баннеры</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.news.update', ['id' => $news->id])}}" class="card">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Новость "{{ $news->title_ru }}"
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_ru">Russian</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_en" class="form-control" name="title_ru" value="{{ $news->title_ru }}" placeholder="Название новости на русском" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_kk">Kazakh</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_kk" class="form-control" name="title_kk" value="{{ $news->title_kk }}" placeholder="Название новости на казахском" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="title_en">English</label>
                                    <div class="col-md-9">
                                        <input type="text" id="title_en" class="form-control" name="title_en" value="{{ $news->title_en }}" placeholder="Название новости на английском" required>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="content_ru">Содержание на русском</label>
                                    <div class="col-md-9">
                                        <textarea id="content_ru" name="content_ru" rows="9" class="form-control trumbowyg" placeholder="">{!! $news->content_ru  !!}</textarea>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="content_kk">Содержание на казахском</label>
                                    <div class="col-md-9">
                                        <textarea id="content_kk" name="content_kk" rows="9" class="form-control trumbowyg" placeholder="">{!! $news->content_kk  !!}</textarea>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="content_en">Содержание на английском</label>
                                    <div class="col-md-9">
                                        <textarea id="content_en" name="content_en" rows="9" class="form-control trumbowyg" placeholder="">{!! $news->content_en  !!}</textarea>
                                    </div>
                                </div>


                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Сохранить</button>
                                <a href="{{ route('admin.news.show', ['page' => $news->id]) }}" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Удалить</a>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/ads/index.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Баннеры</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">
                @for ($i = 1; $i < 5; $i++)
                    <div class="card">
                        <div class="card-header">№{{ $i }}</div>
                        <div class="card-block">
                            <div class="row">
                                <div class="col-md-4">
                                    <form method="post" action="{{ route('admin.ads.update', ['ads' => $i]) }}" enctype="multipart/form-data">
                                        {{ csrf_field() }}
                                        {{ method_field('PUT') }}
                                        <div class="form-group">
                                            URL: <input type="text" class="form-control" name="link" value="{{ $list[$i-1]->link }}" placeholder="Ссылка" required>
                                        </div>
                                        <div class="form-group">
                                            Image: <input type="file" class="form-control" name="image">
                                        </div>
                                        <div>
                                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Сохранить</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-8">
                                    <a href="{{ $list[$i-1]->link }}" target="_blank">
                                        <img src="{{ $list[$i-1]->image }}">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                @endfor


                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/ads/show.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Новости</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.news.destroy', ['id' => $news->id])}}" class="card">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Новость "{{ $news->title_ru }}"
                            </div>
                            <div class="card-block">
                                <h5>Подтвердите удаление. Отменить действие невозможно</h5>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Удалить</button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection