routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Authorization, Content-Type');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Dingo\Api\Routing\Helpers;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/_token', function () {
    return csrf_token();
});

Route::group(['prefix' => 'admin'], function () {

    Route::group(['prefix' => 'account'], function () {
        Route::post('auth', 'Admin\AccountController@auth');
    });

    Route::group(['middleware' => 'checkAdmin'], function () {
        Route::group(['prefix' => 'index'], function () {
            Route::get('digest', 'Admin\AccountController@digest')->name('adminIndex');
        });

        Route::resource('types', 'Admin\TypesController');

        Route::model('terms', App\Models\Reference::class);
        Route::resource('terms', 'Admin\TermsController',  [
            'as' => 'admin'
        ]);

        Route::resource('pages', 'Admin\PagesController',  [
            'as' => 'admin'
        ]);

        Route::resource('news', 'Admin\NewsController',  [
            'as' => 'admin'
        ]);

        Route::resource('ads', 'Admin\AdsController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'tariiff'], function () {
            Route::get('add', 'Admin\TariffController@add')->name('admin.tariff.add');
            Route::get('index', 'Admin\TariffController@index')->name('admin.tariff.index');
            Route::post('store', 'Admin\TariffController@store')->name('admin.tariff.store');
            Route::get('edit/{id}', 'Admin\TariffController@edit')->name('admin.tariff.edit');
            Route::put('update/{id}', 'Admin\TariffController@update')->name('admin.tariff.update');
            Route::get('show/{id}', 'Admin\TariffController@show')->name('admin.tariff.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroy')->name('admin.tariff.destroy');
        });

        Route::group(['prefix' => 'currency'], function () {
            Route::get('add', 'Admin\TariffController@addMoney')->name('admin.currency.add');
            Route::post('store', 'Admin\TariffController@storeMoney')->name('admin.currency.store');
            Route::get('edit/{id}', 'Admin\TariffController@editMoney')->name('admin.currency.edit');
            Route::put('update/{id}', 'Admin\TariffController@updateMoney')->name('admin.currency.update');
            Route::get('show/{id}', 'Admin\TariffController@showMoney')->name('admin.currency.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroyMoney')->name('admin.currency.destroy');
        });

        Route::model('customer','App\Models\Customer');
        Route::resource('customer', 'Admin\CustomerController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'transporter'], function () {
            Route::get('addBalance', 'Admin\TransporterController@formBalance')->name('admin.transporter.formBalance');
            Route::post('addBalance', 'Admin\TransporterController@updateBalance')->name('admin.transporter.updateBalance');

            Route::get('findLocation', 'Admin\TransporterController@findLocation')->name('admin.transporter.findLocation');
            Route::get('approveLocation/{order}', 'Admin\TransporterController@approveLocation')->name('admin.transporter.approveLocation');
            Route::get('deleteLocation/{order}', 'Admin\TransporterController@deleteLocation')->name('admin.transporter.deleteLocation');

            Route::get('deviceChange', 'Admin\TransporterController@deviceChange')->name('admin.transporter.deviceChange');
            Route::get('approveDevice/{token}', 'Admin\TransporterController@approveDevice')->name('admin.transporter.approveDevice');
            Route::get('deleteDevice/{token}', 'Admin\TransporterController@deleteDevice')->name('admin.transporter.deleteDevice');


            Route::get('block/{user}', 'Admin\TransporterController@block')->name('admin.transporter.block');
            Route::post('blockInit/{user}', 'Admin\TransporterController@blockInit')->name('admin.transporter.blockInit');
        });

        Route::model('transporter','App\Models\Transporter');
        Route::resource('transporter', 'Admin\TransporterController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'orders'], function () {
            Route::post('punishing/{id}', 'Admin\OrderController@punishing')->name('admin.orders.punishing');
            Route::get('punish/{id}', 'Admin\OrderController@punish')->name('admin.orders.punish');
            Route::get('moderate/{id}', 'Admin\OrderController@moderate')->name('admin.orders.moderate');
            Route::get('status/{id}', 'Admin\OrderController@byStatus')->name('admin.orders.byStatus');
            Route::get('customer/{id}', 'Admin\OrderController@byCustomer')->name('admin.orders.byCustomer');
            Route::get('transporter/{id}', 'Admin\OrderController@byTransporter')->name('admin.orders.byTransporter');
        });


        Route::resource('order', 'Admin\OrderController',  [
            'as' => 'admin'
        ]);

        Route::resource('location', 'Admin\LocationsController',  [
            'as' => 'admin'
        ]);
    });
});



$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['prefix' => 'v1'], function ($api) {

        $api->group(['prefix' => 'news'], function ($api) {
            $api->get('all', 'App\Http\Controllers\NewsController@all');
            $api->get('fetch/{news}', 'App\Http\Controllers\NewsController@fetch');
        });

        $api->group(['prefix' => 'pages'], function ($api) {
            $api->get('about', 'App\Http\Controllers\PagesController@about');
            $api->get('help', 'App\Http\Controllers\PagesController@help');
            $api->get('map', 'App\Http\Controllers\PagesController@map');
        });


        $api->group(['prefix' => 'customer'], function ($api) {
            $api->group(['prefix' => 'ads'], function ($api) {
                $api->post('list', 'App\Http\Controllers\Customer\AdsController@listing');
            });

            $api->group(['prefix' => 'account'], function ($api) {

                $api->post('signUp', 'App\Http\Controllers\Customer\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Customer\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Customer\AccountController@resetPassword');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('fetch', 'App\Http\Controllers\Customer\AccountController@fetch');
                    $api->post('update', 'App\Http\Controllers\Customer\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Customer\AccountController@setPassword');
                });
            });

            $api->group(['prefix' => 'orders'], function ($api) {
                $api->get('references', 'App\Http\Controllers\Customer\OrdersController@references');
                $api->get('tariff', 'App\Http\Controllers\Customer\OrdersController@tariff');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('add', 'App\Http\Controllers\Customer\OrdersController@addOrder');
                    $api->post('my', 'App\Http\Controllers\Customer\OrdersController@myOrders');
                    $api->post('fetch/{id}', 'App\Http\Controllers\Customer\OrdersController@fetch');
                    $api->post('complete', 'App\Http\Controllers\Customer\OrdersController@complete');
                    $api->post('findLocation/{id}', 'App\Http\Controllers\Customer\OrdersController@findLocation');
                });
            });
        });


        $api->group(['prefix' => 'transporter'], function ($api) {
            $api->group(['prefix' => 'account'], function ($api) {
                $api->post('signUp', 'App\Http\Controllers\Transporter\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Transporter\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Transporter\AccountController@resetPassword');

                $api->group(['middleware' => 'checkDevice'], function ($api) {
                    $api->any('fetch', 'App\Http\Controllers\Transporter\AccountController@fetch');
                    $api->any('update', 'App\Http\Controllers\Transporter\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Transporter\AccountController@setPassword');
                    $api->post('notifications', 'App\Http\Controllers\Transporter\AccountController@notifications');
                });
            });

            $api->group(['prefix' => 'cars', 'middleware' => 'checkDevice'], function ($api) {
                $api->post('myCars', 'App\Http\Controllers\Transporter\CarsController@myCars');
                $api->post('fetchCar', 'App\Http\Controllers\Transporter\CarsController@fetchCar');
                $api->post('addCar', 'App\Http\Controllers\Transporter\CarsController@addCar');
                $api->post('addImage', 'App\Http\Controllers\Transporter\CarsController@addImage');
                $api->any('listOptions', 'App\Http\Controllers\Transporter\CarsController@listOptions');
            });

            $api->group(['prefix' => 'filter', 'middleware' => 'checkDevice'], function ($api) {

app/Http/Controllers/Admin/TransporterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Notification;
use App\Models\Order;
use App\Models\Token;
use App\Models\Transporter;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use DB;
class TransporterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $searchMode = $request->has('search') ? $request->input('search') : false;
        if ($searchMode) {
            $users = DB::table('users')
                ->where('role', '=', 'transporter')
                ->where(function($query) use ($searchMode)
                {
                    $query->where('phone', $searchMode)
                        ->orWhere('iin', $searchMode);
                })
                ->get();
        } else {
            $users = Transporter::init()->get();
        }
        return view('dashboard.transporter.index', compact('users', 'searchMode'));
    }

    public function block($user) {
        $user = User::find($user);
        return view('dashboard.transporter.block', compact('user'));
    }

    public function blockInit($user, Request $request) {
        $user = Transporter::find($user);
        switch($request->input('unit')) {
            default:
            case 'hour':
                $label = 'ч.';
                $factor = 3600;
                break;

            case 'day':
                $label = 'дн.';
                $factor = 86400;
                break;

            case 'week':
                $label = 'нед.';
                $factor = 604800;
                break;

            case 'month':
                $label = 'мес.';
                $factor = 262800;
                break;

            case 'year':
                $label = 'г.';
                $factor = 31536000;
                break;
        }

        $blockTime = $request->input('number') * $factor;
        $message = 'Вы были заблокированы на '.$request->input('number').' '.$label;
        $user->blockTime = time() + $blockTime;

        $user->save();
        $user->notify($message);

        Notification::create([
            'user_id' => $user->id,
            'time' => time(),
            'entity_id' => 0,
            'type' => 'text',
            'text' => $message,
        ]);
        return redirect()->back();
    }

    public function findLocation() {
        $items = DB::table('locate')->where('moderated', 0)->get();
        $list = [];
        foreach($items as $item) {
            $item->order = Order::find($item->order_id);
            $list[] = $item;
        }
        return view('dashboard.transporter.findLocation', compact('list'));
    }

    public function approveLocation($id) {
        $locate = DB::table('locate')->find($id);
        DB::table('locate')->where('id', $id)->update(['moderated' => 1]);
        $order = Order::find($locate->order_id);
        Notification::create([
            'user_id' => $order->transporter_id,
            'time' => time(),
            'entity_id' => $id,
            'type' => 'findLocation',
            'text' => 'Заказчик запрашивает местоположение груза №'.$order->id,
        ]);
        $user = Transporter::find($order->transporter_id);
        $user->notify('Заказчик запрашивает местоположение груза №'.$order->id, $order->id);
        return redirect()->back();
    }

    public function deleteLocation($id) {
        DB::table('locate')->where('id', $id)->delete();
        return redirect()->back();
    }

    public function deviceChange() {
        $list = Token::where('status', 0)->get();
        return view('dashboard.transporter.deviceChange', compact('list'));
    }

    public function approveDevice($token_id) {
        $token = Token::find($token_id);
        $token->status = 1;
        $token->save();

        Token::where('token', $token->user->device_token)->delete();

        $token->user->device_token = $token->token;
        $token->user->save();

        return redirect()->back();
    }

    public function deleteDevice($token_id) {
        $token = Token::find($token_id);
        $token->delete();
        return redirect()->back();
    }

    public function formBalance() {
        return view('dashboard.transporter.formBalance');
    }

    public function updateBalance(Request $request) {
        $errors = $users = [];

        if ($request->hasFile('dump')) {

            $file = $request->dump->store('excel', 'temp');
            $path = public_path().'/uploads/temp/'.$file;
            $data = Excel::load($path, function($reader) {
            })->get();

            if (!empty($data) && $data->count()) {
                foreach ($data as $key => $value) {
                    $user = User::find($value->id);
                    if (!$user) {
                        $errors[] = 'Пользователь с ID '.$value->id .' не найден';
                    }
                    else if ($value->balance == null || $value->balance < 1) {
                        $errors[] = 'Баланс указан неверно ('.$value->balance.') для пользователя с ID '.$value->id;
                    }
                    else {
                        $user->balance+=$value->balance;
                        $user->update();
                        $user->newBalance = $value->balance;
                        $users[] = $user;
                    }
                }
            }

            unlink($path);

        }
        return view('dashboard.transporter.updateBalance', compact('users', 'errors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Transporter $user)
    {
        return view('dashboard.transporter.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Transporter $user)
    {
        return view('dashboard.transporter.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transporter $user)
    {
        $input = $request->all();
        $user->update($input);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transporter $user)
    {
		Token::where('user_id', $user->id)->delete();
        $user->delete();
        return redirect()->route('admin.transporter.index');
    }
}

resources/views/dashboard/transporter/deviceChange.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('adminIndex') }}">Панель управления</a></li>
            <li class="breadcrumb-item active">Смена устройства</li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">
                <div class="row">
                    @foreach($list as $item)
                        <div class="col-sm-6 col-md-4">
                            <div class="card card-default">
                                <div class="card-block">

                                    <h3 class="card-title">Запрос на смену устройства | №{{$item->id}}</h3>
                                    @if (empty($item->user))
                                        <p class="card-text">Ошибка в запросе. Возможно нет пользователя
                                            ID {{ $item->user_id }}</p>
                                    @else
                                        <p class="card-text"><b>Пользователь:</b> <a
                                                    href="{{ route('admin.transporter.edit', ['user' => $item->user->id]) }}">{{ $item->user->name }}</a>
                                        </p>
                                        <p class="card-text"><b>Кодовое слово:</b> {{ $item->user->security_code }}</p>
                                        <p class="card-text"><b>Старое
                                                устройство:</b> {{ \App\Models\Token::where('token', $item->user->device_token)->first()->device }}
                                        </p>
                                        <p class="card-text"><b>Новое устройство:</b> {{ $item->device }}</p>
                                        <div>
                                            <a href="{{ route('admin.transporter.approveDevice', ['token' => $item->id]) }}"
                                               class="btn btn-primary">Сменить устройство</a>
                                            <a href="{{ route('admin.transporter.deleteDevice', ['token' => $item->id]) }}"
                                               class="btn btn-primary">Отклонить запрос</a>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                @endforeach
                <!--/row-->
                </div>
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/transporter/edit.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Перевозчики</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.transporter.update', ['id' => $user->id])}}"
                              class="card">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Перевозчик {{ $user->name }} - ID {{ $user->id }}
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name">НАЗВАНИЕ/ИМЯ</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name" class="form-control" name="name"
                                               value="{{ $user->name }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="phone">ТЕЛЕФОН</label>
                                    <div class="col-md-9">
                                        <input type="text" id="phone" class="form-control" name="phone"
                                               value="{{ $user->phone }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="email">E-MAIL</label>
                                    <div class="col-md-9">
                                        <input type="text" id="email" class="form-control" name="email"
                                               value="{{ $user->email }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="iin">ИИН/БИН</label>
                                    <div class="col-md-9">
                                        <input type="text" id="iin" class="form-control" name="iin"
                                               value="{{ $user->iin }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="actual_address">ФИЗИЧЕСКИЙ
                                        АДРЕС</label>
                                    <div class="col-md-9">
                                        <input type="text" id="actual_address" class="form-control"
                                               name="actual_address" value="{{ $user->actual_address }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="legal_address">ЮРИДИЧЕСКИЙ
                                        АДРЕС</label>
                                    <div class="col-md-9">
                                        <input type="text" id="legal_address" class="form-control" name="legal_address"
                                               value="{{ $user->legal_address }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="balance">БАЛАНС</label>
                                    <div class="col-md-9">
                                        <input type="number" id="balance" class="form-control" name="balance"
                                               value="{{ $user->balance }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="security_code">КОДОВОЕ СЛОВО</label>
                                    <div class="col-md-9">
                                        <input type="text" id="security_code" class="form-control" name="security_code"
                                               value="{{ $user->security_code }}" placeholder="">
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>
                                    Сохранить
                                </button>
                                <a href="{{ route('admin.transporter.show', ['user' => $user->id]) }}"
                                   class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Удалить</a>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/transporter/findLocation.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('adminIndex') }}">Панель управления</a></li>
            <li class="breadcrumb-item active">Запрос местоположения</li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">
                <div class="row">
                    @foreach($list as $item)
                        <div class="col-sm-6 col-md-4">
                            <div class="card card-default">
                                <div class="card-block">
                                    <h3 class="card-title">Запрос местоположения груза №{{$item->order_id}}</h3>
                                    <p class="card-text">Дата запроса: {{ date('d.m.Y', $item->time) }}</p>
                                    <p class="card-text">
                                        Заказчик:
                                        <a href="{{ route('admin.customer.edit', ['customer' => $item->order->customer]) }}">
                                            ID  {{ $item->order->customer->id }}
                                            {{ $item->order->customer->name }}
                                        </a>
                                    </p>
                                    <p class="card-text">
                                        Перевозчик:
                                        <a href="{{ route('admin.transporter.edit', ['transporter' => $item->order->transporter]) }}">
                                            ID  {{ $item->order->transporter->id }}
                                            {{ $item->order->transporter->name }}
                                        </a>
                                    </p>
                                    <div>

                                        <a href="{{ route('admin.transporter.approveLocation', ['order' => $item->id]) }}" class="btn btn-primary">Подтвердить запрос</a>
                                        <a href="{{ route('admin.transporter.deleteLocation', ['order' => $item->id]) }}" class="btn btn-primary">Удалить запрос</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                @endforeach
                <!--/row-->
                </div>
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/transporter/show.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Перевозчик</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.transporter.destroy', ['transporter' => $user->id])}}" class="card">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Перевозчик "{{ $user->name }}"
                            </div>
                            <div class="card-block">
                                <h5>Подтвердите удаление. Отменить действие невозможно</h5>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Удалить</button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection