routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Dingo\Api\Routing\Helpers;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/_token', function () {
    return csrf_token();
});

Route::group(['prefix' => 'admin'], function () {

    Route::group(['prefix' => 'account'], function () {
        Route::post('auth', 'Admin\AccountController@auth');
    });

    Route::group(['middleware' => 'checkAdmin'], function () {
        Route::group(['prefix' => 'index'], function () {
            Route::get('digest', 'Admin\AccountController@digest')->name('adminIndex');
        });

        Route::resource('types', 'Admin\TypesController');

        Route::model('terms', App\Models\Reference::class);
        Route::resource('terms', 'Admin\TermsController',  [
            'as' => 'admin'
        ]);

        Route::resource('pages', 'Admin\PagesController',  [
            'as' => 'admin'
        ]);

        Route::resource('news', 'Admin\NewsController',  [
            'as' => 'admin'
        ]);

        Route::resource('ads', 'Admin\AdsController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'tariiff'], function () {
            Route::get('add', 'Admin\TariffController@add')->name('admin.tariff.add');
            Route::get('index', 'Admin\TariffController@index')->name('admin.tariff.index');
            Route::post('store', 'Admin\TariffController@store')->name('admin.tariff.store');
            Route::get('edit/{id}', 'Admin\TariffController@edit')->name('admin.tariff.edit');
            Route::put('update/{id}', 'Admin\TariffController@update')->name('admin.tariff.update');
            Route::get('show/{id}', 'Admin\TariffController@show')->name('admin.tariff.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroy')->name('admin.tariff.destroy');
        });

        Route::group(['prefix' => 'currency'], function () {
            Route::get('add', 'Admin\TariffController@addMoney')->name('admin.currency.add');
            Route::post('store', 'Admin\TariffController@storeMoney')->name('admin.currency.store');
            Route::get('edit/{id}', 'Admin\TariffController@editMoney')->name('admin.currency.edit');
            Route::put('update/{id}', 'Admin\TariffController@updateMoney')->name('admin.currency.update');
            Route::get('show/{id}', 'Admin\TariffController@showMoney')->name('admin.currency.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroyMoney')->name('admin.currency.destroy');
        });

        Route::model('customer','App\Models\Customer');
        Route::resource('customer', 'Admin\CustomerController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'transporter'], function () {
            Route::get('addBalance', 'Admin\TransporterController@formBalance')->name('admin.transporter.formBalance');
            Route::post('addBalance', 'Admin\TransporterController@updateBalance')->name('admin.transporter.updateBalance');

            Route::get('findLocation', 'Admin\TransporterController@findLocation')->name('admin.transporter.findLocation');
            Route::get('approveLocation/{order}', 'Admin\TransporterController@approveLocation')->name('admin.transporter.approveLocation');
            Route::get('deleteLocation/{order}', 'Admin\TransporterController@deleteLocation')->name('admin.transporter.deleteLocation');

            Route::get('deviceChange', 'Admin\TransporterController@deviceChange')->name('admin.transporter.deviceChange');
            Route::get('approveDevice/{token}', 'Admin\TransporterController@approveDevice')->name('admin.transporter.approveDevice');
            Route::get('deleteDevice/{token}', 'Admin\TransporterController@deleteDevice')->name('admin.transporter.deleteDevice');


            Route::get('block/{user}', 'Admin\TransporterController@block')->name('admin.transporter.block');
            Route::post('blockInit/{user}', 'Admin\TransporterController@blockInit')->name('admin.transporter.blockInit');
        });

        Route::model('transporter','App\Models\Transporter');
        Route::resource('transporter', 'Admin\TransporterController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'orders'], function () {
            Route::post('punishing/{id}', 'Admin\OrderController@punishing')->name('admin.orders.punishing');
            Route::get('punish/{id}', 'Admin\OrderController@punish')->name('admin.orders.punish');
            Route::get('moderate/{id}', 'Admin\OrderController@moderate')->name('admin.orders.moderate');
            Route::get('status/{id}', 'Admin\OrderController@byStatus')->name('admin.orders.byStatus');
            Route::get('customer/{id}', 'Admin\OrderController@byCustomer')->name('admin.orders.byCustomer');
            Route::get('transporter/{id}', 'Admin\OrderController@byTransporter')->name('admin.orders.byTransporter');
        });


        Route::resource('order', 'Admin\OrderController',  [
            'as' => 'admin'
        ]);

        Route::resource('location', 'Admin\LocationsController',  [
            'as' => 'admin'
        ]);
    });
});



$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['prefix' => 'v1'], function ($api) {

        $api->group(['prefix' => 'news'], function ($api) {
            $api->get('all', 'App\Http\Controllers\NewsController@all');
            $api->get('fetch/{news}', 'App\Http\Controllers\NewsController@fetch');
        });

        $api->group(['prefix' => 'pages'], function ($api) {
            $api->get('about', 'App\Http\Controllers\PagesController@about');
            $api->get('help', 'App\Http\Controllers\PagesController@help');
            $api->get('map', 'App\Http\Controllers\PagesController@map');
        });


        $api->group(['prefix' => 'customer'], function ($api) {
            $api->group(['prefix' => 'ads'], function ($api) {
                $api->post('list', 'App\Http\Controllers\Customer\AdsController@listing');
            });

            $api->group(['prefix' => 'account'], function ($api) {

                $api->post('signUp', 'App\Http\Controllers\Customer\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Customer\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Customer\AccountController@resetPassword');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('fetch', 'App\Http\Controllers\Customer\AccountController@fetch');
                    $api->post('update', 'App\Http\Controllers\Customer\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Customer\AccountController@setPassword');
                });
            });

            $api->group(['prefix' => 'orders'], function ($api) {
                $api->get('references', 'App\Http\Controllers\Customer\OrdersController@references');
                $api->get('tariff', 'App\Http\Controllers\Customer\OrdersController@tariff');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('add', 'App\Http\Controllers\Customer\OrdersController@addOrder');
                    $api->post('my', 'App\Http\Controllers\Customer\OrdersController@myOrders');
                    $api->post('fetch/{id}', 'App\Http\Controllers\Customer\OrdersController@fetch');
                    $api->post('complete', 'App\Http\Controllers\Customer\OrdersController@complete');
                    $api->post('findLocation/{id}', 'App\Http\Controllers\Customer\OrdersController@findLocation');
                });
            });
        });


        $api->group(['prefix' => 'transporter'], function ($api) {
            $api->group(['prefix' => 'account'], function ($api) {
                $api->post('signUp', 'App\Http\Controllers\Transporter\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Transporter\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Transporter\AccountController@resetPassword');

                $api->group(['middleware' => 'checkDevice'], function ($api) {
                    $api->any('fetch', 'App\Http\Controllers\Transporter\AccountController@fetch');
                    $api->any('update', 'App\Http\Controllers\Transporter\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Transporter\AccountController@setPassword');
                    $api->post('notifications', 'App\Http\Controllers\Transporter\AccountController@notifications');
                });
            });

            $api->group(['prefix' => 'cars', 'middleware' => 'checkDevice'], function ($api) {
                $api->post('myCars', 'App\Http\Controllers\Transporter\CarsController@myCars');
                $api->post('fetchCar', 'App\Http\Controllers\Transporter\CarsController@fetchCar');
                $api->post('addCar', 'App\Http\Controllers\Transporter\CarsController@addCar');
                $api->post('addImage', 'App\Http\Controllers\Transporter\CarsController@addImage');
                $api->any('listOptions', 'App\Http\Controllers\Transporter\CarsController@listOptions');
            });

            $api->group(['prefix' => 'filter', 'middleware' => 'checkDevice'], function ($api) {
                $api->post('preLoad', 'App\Http\Controllers\Transporter\OrdersController@preLoad');

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Location extends Model
{
    protected $guarded = ['id'];
    public $timestamps = false;
}

app/Http/Controllers/Admin/LocationsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $locations = Location::all();
        return view('dashboard.locations.list', compact('locations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $location = Location::find($id);
        return view('dashboard.locations.edit', compact('location'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $location = Location::find($id);
        $location->update($input);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/locations/create.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Термины</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.terms.store')}}"
                              class="card">
                            {{ csrf_field() }}
                            <input type="hidden" name="type_id" value="{{ $type->id }}"/>
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Добавить термин для типа "{{ $type->name_ru }}"
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ru">Russian</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ru" class="form-control" name="name_ru"
                                               value=" " placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_kk">Kazakh</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_kk" class="form-control" name="name_kk"
                                               value="" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">English</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" class="form-control" name="name_en"
                                               value="" placeholder="">
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>
                                    Добавить
                                </button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/locations/edit.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Локации</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.location.update', ['id' => $location->id])}}"
                              class="card">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Локация {{$location->label_ru }}
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <div id="map" style="width: 100%; height: 300px;"></div>

                                        <script type="text/javascript">
                                            ymaps.ready(function(){
                                                var map = new ymaps.Map("map", {
                                                    center: [{{ $location->coords }}],
                                                    zoom: 12
                                                });
                                            });

                                        </script>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ru">Название (RU)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ru" class="form-control" name="label_ru"
                                               value="{{$location->label_ru }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="label_kz">Название (KZ)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_kk" class="form-control" name="label_kz"
                                               value="{{$location->label_kz }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="label_en">Название (EN)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" class="form-control" name="label_en"
                                               value="{{$location->label_en }}" placeholder="">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="address_ru">Полное название (RU)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="address_ru" class="form-control" name="address_ru"
                                               value="{{$location->address_ru }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="address_kz">Полное название (KZ)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="address_kz" class="form-control" name="address_kz"
                                               value="{{$location->address_kz }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="address_en">Полное название (EN)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="address_en" class="form-control" name="address_en"
                                               value="{{$location->address_en }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="map_id">MAP ID (системное)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="map_id" class="form-control" name=""
                                               value="{{$location->map_id }}" placeholder="" disabled>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="coords">Координаты (системное)</label>
                                    <div class="col-md-9">
                                        <input type="text" id="coords" class="form-control" name=""
                                               value="{{$location->coords }}" placeholder="" disabled>

                                    </div>
                                </div>


                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>
                                    Сохранить
                                </button>
                                <a href="{{ route('admin.terms.show', ['term' => $location->id]) }}"
                                   class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Удалить</a>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/locations/list.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Локации</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Локации
                            </div>
                            <div class="card-block">
                                <table class="table table-bordered table-hover table-condensed">
                                    <thead class="thead-default">
                                    <tr>
                                        <th>ID</th>
                                        <th>НАЗВАНИЕ</th>
                                        <th>ПОЛНОЕ НАЗВАНИЕ</th>
                                        <th>MAP ID</th>
                                        <th>КООРДИНАТЫ</th>
                                        <th>ДЕЙСТВИЯ</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($locations as $item)
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->label_ru }}</td>
                                            <td>{{ $item->address_ru }}</td>
                                            <td>{{ $item->map_id }}</td>
                                            <td>{{ $item->coords }}</td>
                                            <td>
                                                <a href="{{ route('admin.location.edit', ['term' => $item->id]) }}"
                                                   class="btn btn-warning"><i class="icon-pencil"></i> Изменить</a>
                                                <a href="{{ route('admin.location.show', ['term' => $item->id]) }}"
                                                   class="btn btn-danger"><i class="icon-trash"></i> Удалить</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/locations/show.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Термины</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.terms.destroy', ['term' => $ref->id])}}" class="card">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Термин "{{ $ref->name_ru }}"
                            </div>
                            <div class="card-block">
                                <h5>Подтвердите удаление. Отменить действие невозможно</h5>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Удалить</button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection