routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Authorization, Content-Type');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Dingo\Api\Routing\Helpers;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/_token', function () {
    return csrf_token();
});

Route::group(['prefix' => 'admin'], function () {

    Route::group(['prefix' => 'account'], function () {
        Route::post('auth', 'Admin\AccountController@auth');
    });

    Route::group(['middleware' => 'checkAdmin'], function () {
        Route::group(['prefix' => 'index'], function () {
            Route::get('digest', 'Admin\AccountController@digest')->name('adminIndex');
        });

        Route::resource('types', 'Admin\TypesController');

        Route::model('terms', App\Models\Reference::class);
        Route::resource('terms', 'Admin\TermsController',  [
            'as' => 'admin'
        ]);

        Route::resource('pages', 'Admin\PagesController',  [
            'as' => 'admin'
        ]);

        Route::resource('news', 'Admin\NewsController',  [
            'as' => 'admin'
        ]);

        Route::resource('ads', 'Admin\AdsController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'tariiff'], function () {
            Route::get('add', 'Admin\TariffController@add')->name('admin.tariff.add');
            Route::get('index', 'Admin\TariffController@index')->name('admin.tariff.index');
            Route::post('store', 'Admin\TariffController@store')->name('admin.tariff.store');
            Route::get('edit/{id}', 'Admin\TariffController@edit')->name('admin.tariff.edit');
            Route::put('update/{id}', 'Admin\TariffController@update')->name('admin.tariff.update');
            Route::get('show/{id}', 'Admin\TariffController@show')->name('admin.tariff.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroy')->name('admin.tariff.destroy');
        });

        Route::group(['prefix' => 'currency'], function () {
            Route::get('add', 'Admin\TariffController@addMoney')->name('admin.currency.add');
            Route::post('store', 'Admin\TariffController@storeMoney')->name('admin.currency.store');
            Route::get('edit/{id}', 'Admin\TariffController@editMoney')->name('admin.currency.edit');
            Route::put('update/{id}', 'Admin\TariffController@updateMoney')->name('admin.currency.update');
            Route::get('show/{id}', 'Admin\TariffController@showMoney')->name('admin.currency.show');
            Route::delete('destroy/{id}', 'Admin\TariffController@destroyMoney')->name('admin.currency.destroy');
        });

        Route::model('customer','App\Models\Customer');
        Route::resource('customer', 'Admin\CustomerController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'transporter'], function () {
            Route::get('addBalance', 'Admin\TransporterController@formBalance')->name('admin.transporter.formBalance');
            Route::post('addBalance', 'Admin\TransporterController@updateBalance')->name('admin.transporter.updateBalance');

            Route::get('findLocation', 'Admin\TransporterController@findLocation')->name('admin.transporter.findLocation');
            Route::get('approveLocation/{order}', 'Admin\TransporterController@approveLocation')->name('admin.transporter.approveLocation');
            Route::get('deleteLocation/{order}', 'Admin\TransporterController@deleteLocation')->name('admin.transporter.deleteLocation');

            Route::get('deviceChange', 'Admin\TransporterController@deviceChange')->name('admin.transporter.deviceChange');
            Route::get('approveDevice/{token}', 'Admin\TransporterController@approveDevice')->name('admin.transporter.approveDevice');
            Route::get('deleteDevice/{token}', 'Admin\TransporterController@deleteDevice')->name('admin.transporter.deleteDevice');


            Route::get('block/{user}', 'Admin\TransporterController@block')->name('admin.transporter.block');
            Route::post('blockInit/{user}', 'Admin\TransporterController@blockInit')->name('admin.transporter.blockInit');
        });

        Route::model('transporter','App\Models\Transporter');
        Route::resource('transporter', 'Admin\TransporterController',  [
            'as' => 'admin'
        ]);

        Route::group(['prefix' => 'orders'], function () {
            Route::post('punishing/{id}', 'Admin\OrderController@punishing')->name('admin.orders.punishing');
            Route::get('punish/{id}', 'Admin\OrderController@punish')->name('admin.orders.punish');
            Route::get('moderate/{id}', 'Admin\OrderController@moderate')->name('admin.orders.moderate');
            Route::get('status/{id}', 'Admin\OrderController@byStatus')->name('admin.orders.byStatus');
            Route::get('customer/{id}', 'Admin\OrderController@byCustomer')->name('admin.orders.byCustomer');
            Route::get('transporter/{id}', 'Admin\OrderController@byTransporter')->name('admin.orders.byTransporter');
        });


        Route::resource('order', 'Admin\OrderController',  [
            'as' => 'admin'
        ]);

        Route::resource('location', 'Admin\LocationsController',  [
            'as' => 'admin'
        ]);
    });
});



$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['prefix' => 'v1'], function ($api) {

        $api->group(['prefix' => 'news'], function ($api) {
            $api->get('all', 'App\Http\Controllers\NewsController@all');
            $api->get('fetch/{news}', 'App\Http\Controllers\NewsController@fetch');
        });

        $api->group(['prefix' => 'pages'], function ($api) {
            $api->get('about', 'App\Http\Controllers\PagesController@about');
            $api->get('help', 'App\Http\Controllers\PagesController@help');
            $api->get('map', 'App\Http\Controllers\PagesController@map');
        });


        $api->group(['prefix' => 'customer'], function ($api) {
            $api->group(['prefix' => 'ads'], function ($api) {
                $api->post('list', 'App\Http\Controllers\Customer\AdsController@listing');
            });

            $api->group(['prefix' => 'account'], function ($api) {

                $api->post('signUp', 'App\Http\Controllers\Customer\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Customer\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Customer\AccountController@resetPassword');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('fetch', 'App\Http\Controllers\Customer\AccountController@fetch');
                    $api->post('update', 'App\Http\Controllers\Customer\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Customer\AccountController@setPassword');
                });
            });

            $api->group(['prefix' => 'orders'], function ($api) {
                $api->get('references', 'App\Http\Controllers\Customer\OrdersController@references');
                $api->get('tariff', 'App\Http\Controllers\Customer\OrdersController@tariff');

                $api->group(['middleware' => 'checkWeb'], function ($api) {
                    $api->post('add', 'App\Http\Controllers\Customer\OrdersController@addOrder');
                    $api->post('my', 'App\Http\Controllers\Customer\OrdersController@myOrders');
                    $api->post('fetch/{id}', 'App\Http\Controllers\Customer\OrdersController@fetch');
                    $api->post('complete', 'App\Http\Controllers\Customer\OrdersController@complete');
                    $api->post('findLocation/{id}', 'App\Http\Controllers\Customer\OrdersController@findLocation');
                });
            });
        });


        $api->group(['prefix' => 'transporter'], function ($api) {
            $api->group(['prefix' => 'account'], function ($api) {
                $api->post('signUp', 'App\Http\Controllers\Transporter\AccountController@signUp');
                $api->post('signIn', 'App\Http\Controllers\Transporter\AccountController@signIn');
                $api->post('resetPassword', 'App\Http\Controllers\Transporter\AccountController@resetPassword');

                $api->group(['middleware' => 'checkDevice'], function ($api) {
                    $api->any('fetch', 'App\Http\Controllers\Transporter\AccountController@fetch');
                    $api->any('update', 'App\Http\Controllers\Transporter\AccountController@updateProfile');
                    $api->post('setPassword', 'App\Http\Controllers\Transporter\AccountController@setPassword');
                    $api->post('notifications', 'App\Http\Controllers\Transporter\AccountController@notifications');
                });
            });

            $api->group(['prefix' => 'cars', 'middleware' => 'checkDevice'], function ($api) {
                $api->post('myCars', 'App\Http\Controllers\Transporter\CarsController@myCars');
                $api->post('fetchCar', 'App\Http\Controllers\Transporter\CarsController@fetchCar');
                $api->post('addCar', 'App\Http\Controllers\Transporter\CarsController@addCar');
                $api->post('addImage', 'App\Http\Controllers\Transporter\CarsController@addImage');
                $api->any('listOptions', 'App\Http\Controllers\Transporter\CarsController@listOptions');
            });

            $api->group(['prefix' => 'filter', 'middleware' => 'checkDevice'], function ($api) {

app/Http/Controllers/Admin/TermsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Types;
use App\Models\Reference;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TermsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $type_id = $request->has('type') ? $request->input('type') : 1;
        $type = Types::find($type_id);
        $refs = Reference::where('type_id', $type->id)->get();
        return view('dashboard.terms.list', compact('refs', 'type'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $type = Types::find($request->input('type'));
        return view('dashboard.terms.create', compact('type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $ref = Reference::create($input);
        return redirect()->route('admin.terms.edit', ['type' => $ref->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ref = Reference::find($id);
        return view('dashboard.terms.show', compact('ref'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ref = Reference::find($id);
        $models = Reference::getCarBrands();
        return view('dashboard.terms.edit', compact('ref', 'models'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $ref = Reference::find($id);
        $ref->update($input);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ref = Reference::find($id);
        $ref->delete();
        return redirect()->route('admin.terms.index');
    }
}

resources/views/dashboard/terms/create.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Термины</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.terms.store')}}"
                              class="card">
                            {{ csrf_field() }}
                            <input type="hidden" name="type_id" value="{{ $type->id }}"/>
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Добавить термин для типа "{{ $type->name_ru }}"
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ru">Russian</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ru" class="form-control" name="name_ru"
                                               value=" " placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_kk">Kazakh</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_kk" class="form-control" name="name_kk"
                                               value="" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">English</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" class="form-control" name="name_en"
                                               value="" placeholder="">
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>
                                    Добавить
                                </button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/terms/edit.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Термины</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.terms.update', ['id' => $ref->id])}}"
                              class="card">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Термин {{$ref->name_ru }}
                            </div>
                            <div class="card-block">
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_ru">Russian</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_ru" class="form-control" name="name_ru"
                                               value="{{$ref->name_ru }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_kk">Kazakh</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_kk" class="form-control" name="name_kk"
                                               value="{{$ref->name_kk }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="name_en">English</label>
                                    <div class="col-md-9">
                                        <input type="text" id="name_en" class="form-control" name="name_en"
                                               value="{{$ref->name_en }}" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3 form-control-label" for="type_id">Тип данных</label>
                                    <div class="col-md-9">
                                        <select name="type_id" class="form-control" id="type_id">
                                            @foreach($types as $type)
                                                <option value="{{ $type->id }}" @if ($type->id == $ref->type_id) selected @endif>{{ $type->name_ru }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                @if ($ref->type_id == 2)
                                    <div class="form-group row">
                                        <label class="col-md-3 form-control-label" for="parent_id">Модель</label>
                                        <div class="col-md-9">
                                            <select name="parent_id" class="form-control" id="parent_id">
                                                @foreach($models as $model)
                                                    <option value="{{ $model->id }}" @if ($model->id == $ref->parent_id) selected @endif>{{ $model->name_ru }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                @endif

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i>
                                    Сохранить
                                </button>
                                <a href="{{ route('admin.terms.show', ['term' => $ref->id]) }}"
                                   class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Удалить</a>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/terms/list.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Термины</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-xs-12 col-md-12"><a href="{{ route('admin.terms.create', ['type' => $type->id]) }}" class="btn btn-success btn-add"><i class="fa fa-plus"></i>&nbsp; Добавить термин</a></div>

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Термины типа данных "{{ $type->name_ru }}"
                            </div>
                            <div class="card-block">
                                <table class="table table-bordered table-striped table-condensed">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        @if ($type->id ==2) <th>Модель</th> @endif
                                        <th>Russian</th>
                                        <th>Kazakh</th>
                                        <th>English</th>
                                        <th>Действия</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($refs as $ref)
                                        <tr>
                                            <td>{{ $ref->id }}</td>
                                            @if ($type->id ==2) <td>{{ $ref->parent->name_ru }}</td> @endif
                                            <td>{{ $ref->name_ru }}</td>
                                            <td>{{ $ref->name_kk }}</td>
                                            <td>{{ $ref->name_en }}</td>
                                            <td>
                                                <a href="{{ route('admin.terms.edit', ['term' => $ref->id]) }}" class="btn btn-warning"><i class="icon-pencil"></i> Изменить</a>
                                                <a href="{{ route('admin.terms.show', ['term' => $ref->id]) }}" class="btn btn-danger"><i class="icon-trash"></i> Удалить</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection

resources/views/dashboard/terms/show.blade.php
@extends('dashboard.layout')
@section('content')

    <main class="main">
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item"><a href="#">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="#"><i class="icon-speech"></i></a>
                    <a class="btn btn-secondary" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                    <a class="btn btn-secondary" href="#"><i class="icon-settings"></i> &nbsp;Термины</a>
                </div>
            </li>
        </ol>
        <div class="container-fluid">
            <div class="animated fadeIn">

                <!--/row-->

                <!--/row-->
                <div class="row">
                    <div class="col-lg-12">
                        <form method="post" action="{{route('admin.terms.destroy', ['term' => $ref->id])}}" class="card">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i> Термин "{{ $ref->name_ru }}"
                            </div>
                            <div class="card-block">
                                <h5>Подтвердите удаление. Отменить действие невозможно</h5>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Удалить</button>
                            </div>
                        </form>
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>

@endsection